//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CueFunctionParams) DeepCopyInto(out *CueFunctionParams) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CueFunctionParams.
func (in *CueFunctionParams) DeepCopy() *CueFunctionParams {
	if in == nil {
		return nil
	}
	out := new(CueFunctionParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CueFunctionParams) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CueInputSpec) DeepCopyInto(out *CueInputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CueInputSpec.
func (in *CueInputSpec) DeepCopy() *CueInputSpec {
	if in == nil {
		return nil
	}
	out := new(CueInputSpec)
	in.DeepCopyInto(out)
	return out
}
