name: code coverage
on:
  push:
    branches:
      - main
jobs:
  create-coverage-report:
    name: create coverage report
    if:  github.repository == 'crossplane-contrib/function-cue'
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
      - name: run tests
        run: |
          go test ./internal/... -coverprofile=cover.out
      - name: update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: cover.out
          amend: false
          reuse-go: true
        continue-on-error: true
