name: go build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  go-build:
    name: build and test Go code
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - id: go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build, test and lint
        run: |
          make ci
      - name: check dirty files from go generate
        run: |
          make ci-check-dirty
